# Generated by Django 3.0.8 on 2020-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
