# Generated by Django 3.0.8 on 2020-08-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0002_invoice_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
