# Generated by Django 3.0.8 on 2020-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0003_auto_20200802_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
