# Generated by Django 3.0.8 on 2020-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0004_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
